import type { Table } from "aws-cdk-lib/aws-dynamodb";
import { Effect, PolicyStatement } from "aws-cdk-lib/aws-iam";
import {
  Code,
  Function as LambdaFunction,
  Runtime,
} from "aws-cdk-lib/aws-lambda";
import type { IBucket } from "aws-cdk-lib/aws-s3";
import {
  Choice,
  Condition,
  DefinitionBody,
  Fail,
  Pass,
  Result,
  StateMachine,
  Succeed,
  TaskInput,
  Wait,
  WaitTime,
} from "aws-cdk-lib/aws-stepfunctions";
import { LambdaInvoke } from "aws-cdk-lib/aws-stepfunctions-tasks";
import { CfnOutput, Duration, Stack, type StackProps } from "aws-cdk-lib/core";
import { NagSuppressions } from "cdk-nag";
import type { Construct } from "constructs";

/**
 * OrchestrationStack: SageMaker エンドポイントのライフサイクル制御スタック。
 *
 * 旧実装では S3 `input/` への ObjectCreated を EventBridge で拾って
 * 自動的に state machine を起動し、SQS のキュー深度でアイドル判定していたが
 * 本 task 1.1 でそれらを撤去した:
 *   - `mainQueue` props 依存を削除
 *   - `QUEUE_URL` 環境変数と `sqs:GetQueueAttributes` IAM を削除
 *   - S3 EventBridge Rule (legacy `input/` prefix) を削除
 *
 * Task 4.3 で `check_queue_status` (SQS 深度) を廃止し、
 * ControlTable `ACTIVE#COUNT` を参照する `check_batch_in_flight` に置換した。
 * `DeleteEndpoint` の直前で `CheckBatchInFlight` → `WaitForBatches` の
 * ループを挟み、in-flight バッチが 0 になるまでエンドポイント削除を遅延させる。
 */
export interface OrchestrationStackProps extends StackProps {
  controlTable: Table;
  /** 将来の batch 用 EventBridge wiring 向けに bucket への参照を保持する。 */
  bucket: IBucket;
  /** SageMaker エンドポイント名 (呼び出し側で context から解決して渡す)。 */
  endpointName: string;
  /** SageMaker エンドポイント設定名 (呼び出し側で context から解決して渡す)。 */
  endpointConfigName: string;
}

export class OrchestrationStack extends Stack {
  public readonly stateMachine: StateMachine;
  public readonly endpointControlFunction: LambdaFunction;

  constructor(scope: Construct, id: string, props: OrchestrationStackProps) {
    super(scope, id, props);

    const { controlTable, endpointName, endpointConfigName } = props;

    if (!endpointName) {
      throw new Error(
        "endpointName must be provided via OrchestrationStackProps",
      );
    }
    if (!endpointConfigName) {
      throw new Error(
        "endpointConfigName must be provided via OrchestrationStackProps",
      );
    }

    // --- エンドポイント制御 Lambda ---
    this.endpointControlFunction = new LambdaFunction(
      this,
      "EndpointControlFunction",
      {
        runtime: Runtime.PYTHON_3_12,
        handler: "index.handler",
        code: Code.fromAsset("lambda/endpoint-control", {
          exclude: [
            ".venv",
            "__pycache__",
            ".pytest_cache",
            ".coverage",
            "tests",
            ".gitkeep",
          ],
        }),
        timeout: Duration.seconds(30),
        environment: {
          ENDPOINT_NAME: endpointName,
          ENDPOINT_CONFIG_NAME: endpointConfigName,
          CONTROL_TABLE_NAME: controlTable.tableName,
        },
      },
    );

    // --- IAM Permissions ---
    this.endpointControlFunction.addToRolePolicy(
      new PolicyStatement({
        sid: "SageMakerEndpointControl",
        effect: Effect.ALLOW,
        actions: [
          "sagemaker:CreateEndpoint",
          "sagemaker:DeleteEndpoint",
          "sagemaker:DescribeEndpoint",
        ],
        resources: [
          `arn:aws:sagemaker:${this.region}:${this.account}:endpoint/${endpointName}`,
          `arn:aws:sagemaker:${this.region}:${this.account}:endpoint-config/${endpointConfigName}`,
        ],
      }),
    );

    controlTable.grantReadWriteData(this.endpointControlFunction);

    // --- Step Functions ステートマシン ---
    // NOTE: `check_queue_status` ステップは legacy SQS 依存のまま残しているが、
    //       トリガー (EventBridge Rule) を撤去したためこの state machine は
    //       task 4.2 で batch 実行系に合わせて再構築されるまで未起動となる。
    const definition = this.buildStateMachineDefinition(
      this.endpointControlFunction,
    );

    this.stateMachine = new StateMachine(this, "EndpointOrchestrator", {
      definitionBody: DefinitionBody.fromChainable(definition),
      timeout: Duration.hours(2),
    });

    // CDK Nag suppressions
    NagSuppressions.addResourceSuppressions(
      this.endpointControlFunction,
      [
        {
          id: "AwsSolutions-L1",
          reason:
            "Python 3.12 is used for compatibility with yomitoku-client " +
            "which requires Python < 3.13.",
        },
        {
          id: "AwsSolutions-IAM4",
          reason:
            "AWSLambdaBasicExecutionRole is required for CloudWatch Logs. " +
            "This managed policy is the minimum for Lambda execution.",
          appliesTo: [
            "Policy::arn:<AWS::Partition>:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole",
          ],
        },
        {
          id: "AwsSolutions-IAM5",
          reason:
            "DynamoDB grantReadWriteData generates index/* wildcard for GSI access. " +
            "This is the minimum permission generated by CDK L2 grant methods.",
        },
      ],
      true,
    );

    NagSuppressions.addResourceSuppressions(
      this.stateMachine,
      [
        {
          id: "AwsSolutions-IAM5",
          reason:
            "Step Functions execution role wildcards are generated by CDK " +
            "for Lambda invoke permissions.",
        },
        {
          id: "AwsSolutions-SF1",
          reason:
            "CloudWatch Logs for Step Functions will be added in monitoring phase (task 5.1).",
        },
        {
          id: "AwsSolutions-SF2",
          reason:
            "X-Ray tracing for Step Functions will be evaluated in monitoring phase (task 5.1).",
        },
      ],
      true,
    );

    // --- Outputs ---
    new CfnOutput(this, "StateMachineArn", {
      value: this.stateMachine.stateMachineArn,
      description: "Step Functions state machine ARN",
    });

    new CfnOutput(this, "EndpointControlFunctionName", {
      value: this.endpointControlFunction.functionName,
      description: "Endpoint control Lambda function name",
    });
  }

  private buildStateMachineDefinition(controlFn: LambdaFunction) {
    // --- Lambda Invoke tasks ---
    const acquireLock = new LambdaInvoke(this, "AcquireLock", {
      lambdaFunction: controlFn,
      payload: TaskInput.fromObject({
        action: "acquire_lock",
        "execution_id.$": "$$.Execution.Id",
      }),
      resultSelector: { "result.$": "$.Payload" },
      resultPath: "$.lockResult",
    });

    const checkEndpointStatus = new LambdaInvoke(this, "CheckEndpointStatus", {
      lambdaFunction: controlFn,
      payload: TaskInput.fromObject({ action: "check_endpoint_status" }),
      resultSelector: { "result.$": "$.Payload" },
      resultPath: "$.endpointResult",
    });

    const createEndpoint = new LambdaInvoke(this, "CreateEndpoint", {
      lambdaFunction: controlFn,
      payload: TaskInput.fromObject({ action: "create_endpoint" }),
      resultSelector: { "result.$": "$.Payload" },
      resultPath: "$.createResult",
    });

    const waitForEndpoint = new Wait(this, "WaitForEndpoint", {
      time: WaitTime.duration(Duration.seconds(60)),
    });

    const checkEndpointStatusLoop = new LambdaInvoke(
      this,
      "CheckEndpointStatusLoop",
      {
        lambdaFunction: controlFn,
        payload: TaskInput.fromObject({ action: "check_endpoint_status" }),
        resultSelector: { "result.$": "$.Payload" },
        resultPath: "$.endpointResult",
      },
    );

    const deleteEndpoint = new LambdaInvoke(this, "DeleteEndpoint", {
      lambdaFunction: controlFn,
      payload: TaskInput.fromObject({ action: "delete_endpoint" }),
      resultSelector: { "result.$": "$.Payload" },
      resultPath: "$.deleteResult",
    });

    // Task 4.3: ControlTable `ACTIVE#COUNT` を参照して in-flight バッチが
    // 0 件になるまで `DeleteEndpoint` を遅延させる。バッチランナーが
    // TransactWriteItems でカウンタを更新しているため GetItem 単発で判定できる。
    const checkBatchInFlight = new LambdaInvoke(this, "CheckBatchInFlight", {
      lambdaFunction: controlFn,
      payload: TaskInput.fromObject({ action: "check_batch_in_flight" }),
      resultSelector: { "result.$": "$.Payload" },
      resultPath: "$.batchInFlightResult",
    });

    const waitForBatches = new Wait(this, "WaitForBatches", {
      time: WaitTime.duration(Duration.seconds(60)),
    });

    const releaseLock = new LambdaInvoke(this, "ReleaseLock", {
      lambdaFunction: controlFn,
      payload: TaskInput.fromObject({ action: "release_lock" }),
      resultSelector: { "result.$": "$.Payload" },
      resultPath: "$.releaseResult",
    });

    const releaseLockOnError = new LambdaInvoke(this, "ReleaseLockOnError", {
      lambdaFunction: controlFn,
      payload: TaskInput.fromObject({ action: "release_lock" }),
      resultSelector: { "result.$": "$.Payload" },
      resultPath: "$.releaseResult",
    });

    // --- Terminal states ---
    const lockNotAcquired = new Succeed(this, "LockNotAcquired", {
      comment: "Another execution is already controlling the endpoint",
    });

    const done = new Succeed(this, "Done", {
      comment: "Endpoint lifecycle complete",
    });

    const failState = new Fail(this, "ExecutionFailed", {
      cause: "Endpoint orchestration failed after lock release",
    });

    // --- Wait loop counter ---
    const initCounter = new Pass(this, "InitWaitCounter", {
      result: Result.fromObject({ value: 0 }),
      resultPath: "$.waitCount",
    });

    const incrementCounter = new Pass(this, "IncrementWaitCounter", {
      resultPath: "$.waitCount",
      parameters: {
        "value.$": "States.MathAdd($.waitCount.value, 1)",
      },
    });

    // Task 4.3: in-flight バッチ待機ループ用カウンタ
    const initBatchWaitCounter = new Pass(this, "InitBatchWaitCounter", {
      result: Result.fromObject({ value: 0 }),
      resultPath: "$.batchWaitCount",
    });

    const incrementBatchWaitCounter = new Pass(
      this,
      "IncrementBatchWaitCounter",
      {
        resultPath: "$.batchWaitCount",
        parameters: {
          "value.$": "States.MathAdd($.batchWaitCount.value, 1)",
        },
      },
    );

    // --- Flow construction (legacy queue-based checks removed) ---

    // [1] Acquire lock → check result
    const lockChoice = new Choice(this, "LockAcquired?")
      .when(
        Condition.booleanEquals("$.lockResult.result.lock_acquired", true),
        checkEndpointStatus,
      )
      .otherwise(lockNotAcquired);

    acquireLock.next(lockChoice);

    // [2] Check endpoint status → branch
    // Task 4.3: InService のまま即 DeleteEndpoint せず、バッチの in-flight
    // カウンタをチェックしてからエンドポイント停止する。
    const endpointStatusChoice = new Choice(this, "EndpointStatusBranch")
      .when(
        Condition.stringEquals(
          "$.endpointResult.result.endpoint_status",
          "InService",
        ),
        initBatchWaitCounter,
      )
      .when(
        Condition.stringEquals(
          "$.endpointResult.result.endpoint_status",
          "Creating",
        ),
        initCounter,
      )
      .when(
        Condition.stringEquals(
          "$.endpointResult.result.endpoint_status",
          "NOT_FOUND",
        ),
        createEndpoint,
      )
      .otherwise(initCounter);

    checkEndpointStatus.next(endpointStatusChoice);

    // [3] Create endpoint → init counter → wait loop
    createEndpoint.next(initCounter);

    // [4] Wait loop: wait → check → if InService, go to delete
    initCounter.next(waitForEndpoint);
    waitForEndpoint.next(checkEndpointStatusLoop);

    const waitLoopChoice = new Choice(this, "EndpointReady?")
      .when(
        Condition.stringEquals(
          "$.endpointResult.result.endpoint_status",
          "InService",
        ),
        initBatchWaitCounter,
      )
      .when(
        Condition.numberGreaterThanEquals("$.waitCount.value", 20),
        releaseLockOnError.next(failState),
      )
      .otherwise(incrementCounter);

    checkEndpointStatusLoop.next(waitLoopChoice);
    incrementCounter.next(waitForEndpoint);

    // [5a] Batch in-flight 待機ループ: InService の状態から
    //      ControlTable `ACTIVE#COUNT` が 0 になるまで DeleteEndpoint を遅延
    initBatchWaitCounter.next(checkBatchInFlight);

    // Choice は `in_flight_count == 0` を直接判定し、設計書の
    // `concurrentBatchCount == 0` セマンティクスと一致させる。
    const batchInFlightChoice = new Choice(this, "BatchInFlightChoice")
      .when(
        Condition.numberLessThanEquals(
          "$.batchInFlightResult.result.in_flight_count",
          0,
        ),
        deleteEndpoint,
      )
      .when(
        Condition.numberGreaterThanEquals("$.batchWaitCount.value", 120),
        releaseLockOnError,
      )
      .otherwise(incrementBatchWaitCounter);

    checkBatchInFlight.next(batchInFlightChoice);
    incrementBatchWaitCounter.next(waitForBatches);
    waitForBatches.next(checkBatchInFlight);

    // [5b] Delete endpoint → release lock → done
    deleteEndpoint.next(releaseLock);
    releaseLock.next(done);

    // Error handling: add catch to all Lambda invokes
    const errorHandler = releaseLockOnError;

    // acquireLock failure: lock was not acquired, so skip release and fail directly
    acquireLock.addCatch(failState, { resultPath: "$.error" });

    for (const task of [
      checkEndpointStatus,
      createEndpoint,
      checkEndpointStatusLoop,
      checkBatchInFlight,
      deleteEndpoint,
      releaseLock,
    ]) {
      task.addCatch(errorHandler, {
        resultPath: "$.error",
      });
    }

    return acquireLock;
  }
}
